In [1]:
import pickle as pkl
import numpy as np

In [2]:
with open('Train_twenty.pkl', 'rb') as tr:
    X_train = pkl.load(tr)
tr.close()
X_train

array([[0.09677419, 0.        , 0.06451613, ..., 0.00420168, 0.05042017,
        0.07142857],
       [0.05      , 0.        , 0.        , ..., 0.01459854, 0.05839416,
        0.06569343],
       [0.14285715, 0.04081633, 0.02040816, ..., 0.01604278, 0.05614973,
        0.05882353],
       ...,
       [0.        , 0.        , 0.        , ..., 0.00406504, 0.05691057,
        0.07317073],
       [0.01587302, 0.01587302, 0.        , ..., 0.00429185, 0.07296138,
        0.06866953],
       [0.        , 0.        , 0.        , ..., 0.        , 0.1       ,
        0.05555556]], dtype=float32)

In [3]:
with open('Val_twenty.pkl', 'rb') as val:
    X_val = pkl.load(val)
val.close()
X_val

array([[0.01941748, 0.        , 0.        , ..., 0.00387597, 0.04134367,
        0.05297158],
       [0.0625    , 0.        , 0.0625    , ..., 0.00769231, 0.03846154,
        0.06923077],
       [0.09090909, 0.03030303, 0.        , ..., 0.0037037 , 0.01851852,
        0.07037037],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.08074534,
        0.03726708],
       [0.        , 0.02380952, 0.        , ..., 0.00527705, 0.05013192,
        0.06860159],
       [0.01666667, 0.00833333, 0.        , ..., 0.00221484, 0.03543743,
        0.04318937]], dtype=float32)

In [4]:
with open('Test_twenty.pkl', 'rb') as test:
    X_test = pkl.load(test)
test.close()
X_test

array([[0.04761905, 0.        , 0.        , ..., 0.0030581 , 0.06116208,
        0.06116208],
       [0.20833333, 0.        , 0.04166667, ..., 0.        , 0.07058824,
        0.05882353],
       [0.12903225, 0.        , 0.03225806, ..., 0.        , 0.05785124,
        0.04545455],
       ...,
       [0.        , 0.        , 0.        , ..., 0.00422833, 0.03171247,
        0.06553911],
       [0.        , 0.        , 0.02777778, ..., 0.00386399, 0.03323029,
        0.04250386],
       [0.        , 0.        , 0.        , ..., 0.        , 0.04347826,
        0.04347826]], dtype=float32)

In [5]:
with open('Train_labels.txt', 'r') as l:
    train_labels = l.read().split('\n')
l.close()
len(train_labels)

87844

In [6]:
with open('Val_labels.txt', 'r') as v:
    val_labels = v.read().split('\n')
v.close()
len(val_labels)

1000

In [7]:
with open('Test_labels.txt', 'r') as t:
    test_labels = t.read().split('\n')
t.close()
len(test_labels)

1000

In [8]:
from sklearn.metrics import confusion_matrix, classification_report

## BAYES

In [9]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, ComplementNB, BernoulliNB

In [10]:
gauss = GaussianNB()
gauss.fit(X_train, train_labels)

GaussianNB(priors=None, var_smoothing=1e-09)

In [11]:
gauss.score(X_val, val_labels), gauss.score(X_test, test_labels)

(0.623, 0.606)

In [12]:
confusion_matrix(gauss.predict(X_test), test_labels)

array([[60,  2,  0,  1,  0,  0,  0,  3,  0,  2],
       [ 4, 75,  1,  1,  0,  1,  2,  1,  4,  4],
       [ 3,  1, 69,  7,  5,  0,  7,  3,  0,  6],
       [ 2,  5,  3, 64,  0,  0,  3,  5,  0,  4],
       [ 1,  2,  1,  0, 80,  1,  1,  3, 21, 10],
       [ 2,  2,  6,  6,  2, 89, 15, 12,  6, 23],
       [24, 10, 14, 15,  5,  7, 66, 13, 22, 28],
       [ 1,  0,  4,  5,  2,  2,  6, 57, 19,  1],
       [ 1,  2,  1,  1,  2,  0,  0,  3, 24,  0],
       [ 2,  1,  1,  0,  4,  0,  0,  0,  4, 22]], dtype=int64)

In [13]:
print(classification_report(gauss.predict(X_test), test_labels))

              precision    recall  f1-score   support

       Anime       0.60      0.88      0.71        68
         Art       0.75      0.81      0.78        93
       Books       0.69      0.68      0.69       101
       Films       0.64      0.74      0.69        86
        Food       0.80      0.67      0.73       120
    Football       0.89      0.55      0.68       163
       Games       0.66      0.32      0.43       204
       Music       0.57      0.59      0.58        97
      Nature       0.24      0.71      0.36        34
      Travel       0.22      0.65      0.33        34

    accuracy                           0.61      1000
   macro avg       0.61      0.66      0.60      1000
weighted avg       0.68      0.61      0.62      1000



In [15]:
multinom = MultinomialNB()
multinom.fit(X_train, train_labels)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [16]:
multinom.score(X_val, val_labels), multinom.score(X_test, test_labels)

(0.135, 0.131)

In [17]:
multinom.fit(X_val, val_labels)
multinom.score(X_test, test_labels)

0.641

In [24]:
print(classification_report(multinom.predict(X_test), test_labels))

              precision    recall  f1-score   support

       Anime       0.71      0.77      0.74        92
         Art       0.67      0.88      0.76        76
       Books       0.73      0.74      0.74        98
       Films       0.72      0.70      0.71       103
        Food       0.70      0.80      0.74        88
    Football       0.73      0.69      0.71       106
       Games       0.47      0.47      0.47        99
       Music       0.49      0.64      0.56        76
      Nature       0.53      0.47      0.50       112
      Travel       0.66      0.44      0.53       150

    accuracy                           0.64      1000
   macro avg       0.64      0.66      0.65      1000
weighted avg       0.64      0.64      0.64      1000



In [19]:
confusion_matrix(multinom.predict(X_test), test_labels)

array([[71,  4,  0,  1,  4,  1,  5,  2,  2,  2],
       [ 2, 67,  0,  0,  0,  0,  0,  0,  4,  3],
       [ 2,  3, 73,  5,  1,  0,  4,  2,  2,  6],
       [ 1,  4,  8, 72,  0,  1,  2,  8,  2,  5],
       [ 2,  0,  0,  0, 70,  0,  0,  1, 11,  4],
       [ 5,  3,  3,  4,  3, 73,  4,  5,  0,  6],
       [ 4,  6,  8,  6,  5,  6, 47,  9,  3,  5],
       [ 1,  1,  1,  1,  3,  3,  4, 49, 12,  1],
       [ 3,  6,  1,  6,  7,  9,  8, 17, 53,  2],
       [ 9,  6,  6,  5,  7,  7, 26,  7, 11, 66]], dtype=int64)

In [25]:
comp = ComplementNB()
comp.fit(X_train, train_labels)

ComplementNB(alpha=1.0, class_prior=None, fit_prior=True, norm=False)

In [26]:
comp.score(X_val, val_labels), comp.score(X_test, test_labels)

(0.545, 0.532)

In [27]:
print(classification_report(comp.predict(X_test), test_labels))

              precision    recall  f1-score   support

       Anime       0.51      0.84      0.63        61
         Art       0.47      0.87      0.61        54
       Books       0.77      0.54      0.63       143
       Films       0.70      0.62      0.66       113
        Food       0.80      0.59      0.68       136
    Football       0.82      0.50      0.62       165
       Games       0.71      0.37      0.49       192
       Music       0.54      0.40      0.46       136
      Nature       0.00      0.00      0.00         0
      Travel       0.00      0.00      0.00         0

    accuracy                           0.53      1000
   macro avg       0.53      0.47      0.48      1000
weighted avg       0.70      0.53      0.59      1000



c:\users\1\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [28]:
comp.fit(X_val, val_labels).score(X_test, test_labels)

0.594

In [29]:
bern = BernoulliNB()
bern.fit(X_train, train_labels)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [30]:
bern.score(X_val, val_labels), bern.score(X_test, test_labels)

(0.449, 0.425)

In [31]:
print(classification_report(bern.predict(X_test), test_labels))

              precision    recall  f1-score   support

       Anime       0.20      0.71      0.31        28
         Art       0.34      0.61      0.44        56
       Books       0.65      0.41      0.51       157
       Films       0.50      0.47      0.48       107
        Food       0.66      0.61      0.63       108
    Football       0.76      0.48      0.59       158
       Games       0.76      0.26      0.39       290
       Music       0.38      0.40      0.39        94
      Nature       0.00      0.00      0.00         2
      Travel       0.00      0.00      0.00         0

    accuracy                           0.42      1000
   macro avg       0.42      0.40      0.37      1000
weighted avg       0.63      0.42      0.48      1000



c:\users\1\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [32]:
bern.fit(X_val, val_labels).score(X_test, test_labels)

0.504

In [33]:
print(classification_report(bern.predict(X_test), test_labels))

              precision    recall  f1-score   support

       Anime       0.53      0.55      0.54        97
         Art       0.68      0.58      0.62       118
       Books       0.58      0.51      0.54       113
       Films       0.63      0.51      0.56       124
        Food       0.68      0.59      0.63       116
    Football       0.64      0.61      0.62       105
       Games       0.48      0.41      0.44       116
       Music       0.35      0.45      0.40        77
      Nature       0.34      0.39      0.36        88
      Travel       0.13      0.28      0.18        46

    accuracy                           0.50      1000
   macro avg       0.50      0.49      0.49      1000
weighted avg       0.54      0.50      0.52      1000



## SVM

In [34]:
from sklearn.svm import LinearSVC

In [35]:
lsvc = LinearSVC(random_state=0, tol=1e-4)
lsvc.fit(X_train, train_labels)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=0, tol=0.0001,
          verbose=0)

In [36]:
lsvc.score(X_val, val_labels), lsvc.score(X_test, test_labels)

(0.523, 0.523)

In [37]:
lsvc.fit(X_val, val_labels).score(X_test, test_labels)

0.647

In [38]:
confusion_matrix(lsvc.predict(X_test), test_labels)

array([[77,  4,  0,  1,  4,  1, 11,  5,  2,  3],
       [ 2, 74,  0,  1,  0,  0,  0,  2,  4,  3],
       [ 4,  2, 76,  6,  3,  2,  7,  5,  5,  8],
       [ 1,  4,  8, 75,  0,  1,  3,  9,  1,  6],
       [ 3,  0,  0,  0, 77,  0,  0,  0, 16,  9],
       [ 2,  2,  6,  4,  2, 76,  5,  7,  2,  8],
       [ 5,  8,  5,  5,  5, 10, 49,  9,  5,  8],
       [ 0,  0,  1,  3,  4,  4,  4, 52, 18,  2],
       [ 3,  4,  2,  1,  3,  2,  4,  7, 38,  0],
       [ 3,  2,  2,  4,  2,  4, 17,  4,  9, 53]], dtype=int64)

In [39]:
print(classification_report(lsvc.predict(X_test), test_labels))

              precision    recall  f1-score   support

       Anime       0.77      0.71      0.74       108
         Art       0.74      0.86      0.80        86
       Books       0.76      0.64      0.70       118
       Films       0.75      0.69      0.72       108
        Food       0.77      0.73      0.75       105
    Football       0.76      0.67      0.71       114
       Games       0.49      0.45      0.47       109
       Music       0.52      0.59      0.55        88
      Nature       0.38      0.59      0.46        64
      Travel       0.53      0.53      0.53       100

    accuracy                           0.65      1000
   macro avg       0.65      0.65      0.64      1000
weighted avg       0.66      0.65      0.65      1000



## K nearest

In [40]:
from sklearn.neighbors import KNeighborsClassifier

In [41]:
kn = KNeighborsClassifier()
kn.fit(X_train, train_labels)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [42]:
kn.score(X_val, val_labels), kn.score(X_test, test_labels)

(0.553, 0.54)

In [43]:
kn.fit(X_val, val_labels).score(X_test, test_labels)

0.581

## Ensembles

In [44]:
from sklearn.ensemble import RandomForestClassifier, VotingClassifier

In [45]:
rfc = RandomForestClassifier(n_estimators = 100)
rfc.fit(X_train, train_labels)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [46]:
rfc.score(X_val, val_labels), rfc.score(X_test, test_labels)

(0.574, 0.561)

In [38]:
rfc.fit(X_val, val_labels).score(X_test, test_labels)

0.6506506506506506

In [48]:
print(classification_report(rfc.predict(X_test), test_labels))

              precision    recall  f1-score   support

       Anime       0.56      0.93      0.70        60
         Art       0.52      0.88      0.65        59
       Books       0.73      0.70      0.72       104
       Films       0.64      0.75      0.69        85
        Food       0.78      0.72      0.75       108
    Football       0.82      0.59      0.69       139
       Games       0.87      0.27      0.41       323
       Music       0.49      0.49      0.49       101
      Nature       0.10      0.91      0.18        11
      Travel       0.10      1.00      0.18        10

    accuracy                           0.56      1000
   macro avg       0.56      0.72      0.55      1000
weighted avg       0.73      0.56      0.58      1000



In [56]:
cl1 = MultinomialNB()
cl2 = LinearSVC()
cl3 = RandomForestClassifier(n_estimators = 100)

In [57]:
vt = VotingClassifier(estimators = [('nb', cl1), ('svc', cl2), ('rfc', cl3)], voting='hard')

In [58]:
vt.fit(X_train, train_labels)

VotingClassifier(estimators=[('nb',
                              MultinomialNB(alpha=1.0, class_prior=None,
                                            fit_prior=True)),
                             ('svc',
                              LinearSVC(C=1.0, class_weight=None, dual=True,
                                        fit_intercept=True, intercept_scaling=1,
                                        loss='squared_hinge', max_iter=1000,
                                        multi_class='ovr', penalty='l2',
                                        random_state=None, tol=0.0001,
                                        verbose=0)),
                             ('rfc',
                              RandomForestClassifier(bootstrap=True,
                                                     class_weight=None,
                                                     criterion='gini',
                                                     max_depth=None,
                                          

In [59]:
vt.score(X_val, val_labels), vt.score(X_test, test_labels)

(0.518, 0.528)

In [60]:
vt.fit(X_val, val_labels).score(X_test, test_labels)

0.66

In [61]:
print(classification_report(vt.predict(X_test), test_labels))

              precision    recall  f1-score   support

       Anime       0.76      0.72      0.74       105
         Art       0.73      0.86      0.79        85
       Books       0.77      0.71      0.74       108
       Films       0.74      0.70      0.72       105
        Food       0.75      0.74      0.74       102
    Football       0.75      0.69      0.72       109
       Games       0.51      0.46      0.49       110
       Music       0.53      0.63      0.58        84
      Nature       0.46      0.57      0.51        81
      Travel       0.60      0.54      0.57       111

    accuracy                           0.66      1000
   macro avg       0.66      0.66      0.66      1000
weighted avg       0.67      0.66      0.66      1000

